import { Category, Product } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Seating', slug: 'seating' },
  { id: 'c2', name: 'Tables', slug: 'tables' },
  { id: 'c3', name: 'Storage & Shelving', slug: 'storage' },
  { id: 'c4', name: 'Lighting & Decor', slug: 'lighting' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Aura Velvet Accent Armchair',
    slug: 'aura-velvet-accent-armchair',
    description:
      'Sculptural lounge chair featuring plush velvet upholstery over a solid oak frame. Ergonomically contoured for effortless lounge comfort with timeless editorial warmth.',
    price: 1250,
    category_id: 'c1',
    category: { id: 'c1', name: 'Seating', slug: 'seating' },
    image_url: '/collections/if001.jpg',
    gallery: [
      { label: 'Front Elevation', url: '/collections/if001.jpg' },
      { label: 'Architectural Profile', url: '/collections/if002.jpg' },
      { label: 'Detail Joinery & Texture', url: '/collections/if003.jpg' },
      { label: 'In-Situ Living Context', url: '/collections/if004.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'W 34" x D 32" x H 30" | Seat H 17"',
    materials: 'Solid White Oak, Artisanal Upholstery, High-Density Resilient Core',
  },
  {
    id: 'p2',
    name: 'Kanso Organic Walnut Dining Table',
    slug: 'kanso-organic-walnut-dining-table',
    description:
      'Crafted from sustainably harvested solid American Walnut, the Kanso dining centerpiece highlights continuous wood grain movement with softened bevel edges.',
    price: 2890,
    category_id: 'c2',
    category: { id: 'c2', name: 'Tables', slug: 'tables' },
    image_url: '/collections/if005.jpg',
    gallery: [
      { label: 'Full Table Silhouette', url: '/collections/if005.jpg' },
      { label: 'Tapered Leg & Tenon Joint', url: '/collections/if006.jpg' },
      { label: 'Solid Timber Surface Macro', url: '/collections/if007.jpg' },
      { label: 'Dining Pavilion Ambience', url: '/collections/if008.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'L 84" x W 38" x H 30"',
    materials: '100% Solid Hardwood, Hand-Rubbed Botanical Hardwax Oil Finish',
  },
  {
    id: 'p3',
    name: 'Mirei Bouclé Modular Sofa',
    slug: 'mirei-boucle-modular-sofa',
    description:
      'Extravagant cloud-like seating upholstered in soft ivory tactile bouclé fabric. Generous proportions designed for relaxed formal hosting and timeless living.',
    price: 3450,
    category_id: 'c1',
    category: { id: 'c1', name: 'Seating', slug: 'seating' },
    image_url: '/collections/if009.jpg',
    gallery: [
      { label: 'Modular Front View', url: '/collections/if009.jpg' },
      { label: 'Deep Contour Side Profile', url: '/collections/if010.jpg' },
      { label: 'Tactile Bouclé Fabric Weave', url: '/collections/if011.jpg' },
      { label: 'Architectural Salon Setting', url: '/collections/if012.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'W 108" x D 42" x H 28" | Seat H 16.5"',
    materials: 'Textured Bouclé, Feather & Down Fill, Kiln-Dried Solid Frame',
  },
  {
    id: 'p4',
    name: 'Lumina Travertine Floor Monolith',
    slug: 'lumina-travertine-floor-monolith',
    description:
      'Architectural monolith floor fixture anchored by a carved natural travertine stone base with brushed warm brass hardware and hand-loomed shade.',
    price: 780,
    category_id: 'c4',
    category: { id: 'c4', name: 'Lighting & Decor', slug: 'lighting' },
    image_url: '/collections/if013.jpg',
    gallery: [
      { label: 'Full Monolith Elevation', url: '/collections/if013.jpg' },
      { label: 'Travertine Stone Veining', url: '/collections/if014.jpg' },
      { label: 'Brushed Brass Detailing', url: '/collections/if015.jpg' },
      { label: 'Evening Ambience Context', url: '/collections/if016.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'Base Dia 12" x H 64" | Shade Dia 18"',
    materials: 'Honed Natural Travertine, Antique Brass, Natural Fiber',
  },
  {
    id: 'p5',
    name: 'Solstice Credenza Sideboard',
    slug: 'solstice-credenza-sideboard',
    description:
      'Mid-century minimalist sideboard featuring fluted tambour solid oak sliding doors, brass hardware accents, and integrated cable routing for media or dining storage.',
    price: 2150,
    category_id: 'c3',
    category: { id: 'c3', name: 'Storage & Shelving', slug: 'storage' },
    image_url: '/collections/if017.jpg',
    gallery: [
      { label: 'Front Credenza View', url: '/collections/if017.jpg' },
      { label: 'Fluted Tambour Sliding Slats', url: '/collections/if018.jpg' },
      { label: 'Joinery & Brass Pulls', url: '/collections/if019.jpg' },
      { label: 'Living Room Architecture', url: '/collections/if020.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'W 72" x D 19" x H 31"',
    materials: 'Solid Hardwood, Handcrafted Tambour, Soft-Close Brass Hinges',
  },
  {
    id: 'p6',
    name: 'Brutalist Smoked Glass Coffee Table',
    slug: 'brutalist-smoked-glass-coffee-table',
    description:
      'Thick tempered smoked glass resting atop twin sculptural cast-concrete pedestal blocks. A bold centerpiece fixture for contemporary living rooms.',
    price: 1420,
    category_id: 'c2',
    category: { id: 'c2', name: 'Tables', slug: 'tables' },
    image_url: '/collections/if021.jpg',
    gallery: [
      { label: 'Overview & Reflection Angle', url: '/collections/if021.jpg' },
      { label: 'Sculptural Base Pedestal', url: '/collections/if022.jpg' },
      { label: 'Beveled Smoked Glass Rim', url: '/collections/if023.jpg' },
      { label: 'Atmospheric Salon Interior', url: '/collections/if024.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'L 52" x W 32" x H 14"',
    materials: '12mm Tempered Smoked Glass, Sealed Architectural Stone Base',
  },
  {
    id: 'p7',
    name: 'Sora Sculptural Occasional Lounge',
    slug: 'sora-sculptural-occasional-lounge',
    description:
      'A masterclass in organic curvature. Features continuous steam-bent hardwood architecture paired with bespoke woven textile cushions.',
    price: 1850,
    category_id: 'c1',
    category: { id: 'c1', name: 'Seating', slug: 'seating' },
    image_url: '/collections/if025.jpg',
    gallery: [
      { label: 'Curvilinear Front', url: '/collections/if025.jpg' },
      { label: 'Rear Archival Curves', url: '/collections/if026.jpg' },
      { label: 'Hand-Stitched Hem Detail', url: '/collections/if027.jpg' },
      { label: 'Sunlight Gallery Interior', url: '/collections/if028.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'W 36" x D 34" x H 31"',
    materials: 'Steam-Bent Solid Ash, Textured Natural Linen',
  },
  {
    id: 'p8',
    name: 'Kyoto Minimalist Low Credenza',
    slug: 'kyoto-minimalist-low-credenza',
    description:
      'Inspired by Japanese joinery traditions. Features concealed finger-groove pulls, floating plinth base, and continuous horizontal wood grain.',
    price: 2450,
    category_id: 'c3',
    category: { id: 'c3', name: 'Storage & Shelving', slug: 'storage' },
    image_url: '/collections/if029.jpg',
    gallery: [
      { label: 'Full Elevation', url: '/collections/if029.jpg' },
      { label: 'Finger Pull & Grain Flow', url: '/collections/if030.jpg' },
      { label: 'Corner Dovetail Joint', url: '/collections/if031.jpg' },
      { label: 'Modern Sanctuary Setting', url: '/collections/if032.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'W 80" x D 20" x H 24"',
    materials: 'Solid White Oak, Natural Linseed Oil Polish',
  },
  {
    id: 'p9',
    name: 'Vessel Honed Travertine Side Table',
    slug: 'vessel-honed-travertine-side-table',
    description:
      'Carved from a singular block of unpolished Roman travertine with tactile fluting and a subtly dished circular tabletop.',
    price: 920,
    category_id: 'c2',
    category: { id: 'c2', name: 'Tables', slug: 'tables' },
    image_url: '/collections/if033.jpg',
    gallery: [
      { label: 'Pedestal Silhouette', url: '/collections/if033.jpg' },
      { label: 'Fluted Column Details', url: '/collections/if034.jpg' },
      { label: 'Natural Stone Porosity Macro', url: '/collections/if035.jpg' },
      { label: 'Beside Lounge Context', url: '/collections/if036.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'Dia 18" x H 22"',
    materials: '100% Honed Italian Travertine Stone',
  },
  {
    id: 'p10',
    name: 'Atelier Solid Timber Bookcase',
    slug: 'atelier-solid-timber-bookcase',
    description:
      'Open architectural framework designed for curated objets d’art, monographs, and sculptures with asymmetric vertical dividers.',
    price: 3100,
    category_id: 'c3',
    category: { id: 'c3', name: 'Storage & Shelving', slug: 'storage' },
    image_url: '/collections/if037.jpg',
    gallery: [
      { label: 'Full Framework View', url: '/collections/if037.jpg' },
      { label: 'Interlocking Shelf Joint', url: '/collections/if038.jpg' },
      { label: 'Solid Wood Grain Texture', url: '/collections/if039.jpg' },
      { label: 'Study & Library Ambience', url: '/collections/if040.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'W 60" x D 16" x H 78"',
    materials: 'Kiln-Dried Walnut, Brass Mortise Dowels',
  },
  {
    id: 'p11',
    name: 'Elysian High-Back Executive Armchair',
    slug: 'elysian-high-back-executive-armchair',
    description:
      'Commanding posture with enveloping wing contours. Upholstered in full-grain vegetable-tanned leather over a hand-carved wood frame.',
    price: 2600,
    category_id: 'c1',
    category: { id: 'c1', name: 'Seating', slug: 'seating' },
    image_url: '/collections/if041.jpg',
    gallery: [
      { label: 'Front Wing Silhouette', url: '/collections/if041.jpg' },
      { label: 'Side Ergonomic Arc', url: '/collections/if042.jpg' },
      { label: 'Leather Stitching & Buttoning', url: '/collections/if043.jpg' },
      { label: 'Executive Office Setting', url: '/collections/if044.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'W 32" x D 35" x H 44"',
    materials: 'Vegetable-Tanned Saddle Leather, Solid Ebony Stained Ash',
  },
  {
    id: 'p12',
    name: 'Pavilion Round Gathering Dining Table',
    slug: 'pavilion-round-gathering-dining-table',
    description:
      'Circular gathering table with a conical fluted pedestal base. Perfect for intimate conversations and expansive dinner hosting.',
    price: 3250,
    category_id: 'c2',
    category: { id: 'c2', name: 'Tables', slug: 'tables' },
    image_url: '/collections/if045.jpg',
    gallery: [
      { label: 'Circular Table Top', url: '/collections/if045.jpg' },
      { label: 'Fluted Pedestal Column', url: '/collections/if046.jpg' },
      { label: 'Radial Timber Veneer Pattern', url: '/collections/if047.jpg' },
      { label: 'Dining Space Architecture', url: '/collections/if048.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'Dia 60" x H 30"',
    materials: 'Solid White Oak & Radial Oak Inlay',
  },
  {
    id: 'p13',
    name: 'Monolith Architectural Bench',
    slug: 'monolith-architectural-bench',
    description:
      'Low, solid bench crafted from monolithic timber slabs with exposed joinery. Ideal for gallery entries or at the foot of bespoke bedframes.',
    price: 1100,
    category_id: 'c1',
    category: { id: 'c1', name: 'Seating', slug: 'seating' },
    image_url: '/collections/if049.jpg',
    gallery: [
      { label: 'Bench Profile', url: '/collections/if049.jpg' },
      { label: 'Exposed Tenon Detail', url: '/collections/if050.jpg' },
      { label: 'Timber Edge Texture', url: '/collections/if051.jpg' },
      { label: 'Foyer Architecture View', url: '/collections/if052.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'L 64" x W 18" x H 17"',
    materials: 'Solid Hardwood, Natural Matte Wax',
  },
  {
    id: 'p14',
    name: 'Halo Ambient Chandelier & Sconce',
    slug: 'halo-ambient-chandelier-sconce',
    description:
      'Suspended sculptural light fixture combining hand-blown frosted glass globes with brushed unlacquered brass suspension rods.',
    price: 1350,
    category_id: 'c4',
    category: { id: 'c4', name: 'Lighting & Decor', slug: 'lighting' },
    image_url: '/collections/if053.jpg',
    gallery: [
      { label: 'Pendant Overview', url: '/collections/if053.jpg' },
      { label: 'Frosted Glass Globe Diffuser', url: '/collections/if054.jpg' },
      { label: 'Brass Swivel Fixture', url: '/collections/if055.jpg' },
      { label: 'Dining Room Lighting Effect', url: '/collections/if056.jpg' },
    ],
    in_stock: true,
    featured: false,
    dimensions: 'Dia 36" x Adjustable Drop 24"-60"',
    materials: 'Mouth-Blown Opaline Glass, Solid Brushed Brass',
  },
  {
    id: 'p15',
    name: 'Zenith Sculptural Media Console',
    slug: 'zenith-sculptural-media-console',
    description:
      'Low-profile living room media console with acoustic cloth door panels, solid timber framing, and precision soft-closing hardware.',
    price: 2700,
    category_id: 'c3',
    category: { id: 'c3', name: 'Storage & Shelving', slug: 'storage' },
    image_url: '/collections/if057.jpg',
    gallery: [
      { label: 'Console Front View', url: '/collections/if057.jpg' },
      { label: 'Acoustic Slat Inlay', url: '/collections/if058.jpg' },
      { label: 'Cable Channel & Soft-Close', url: '/collections/if059.jpg' },
      { label: 'Living Pavilion Ambience', url: '/collections/if001.jpg' },
    ],
    in_stock: true,
    featured: true,
    dimensions: 'W 84" x D 20" x H 22"',
    materials: 'Solid American Walnut, Natural Wool-Blend Acoustic Mesh',
  },
];
